/**
 * @note Lookup importing modules in typescript.
 */

import domtoimage from "dom-to-image";

/**
 * @summary This function generates image and returns the dataUrl of the same.
 * @return {Promise<string>} This return dataUrl of the image generate via dom-to-image npm module if successful else pops-up an alert.
 */

const generateImage = async (): Promise<string> => {
  let dataUrl: string = "";
  try {
    dataUrl = await domtoimage.toPng(document.querySelector("#card__image"));
  } catch (e) {
    window.alert(e);
  }
  return dataUrl;
};

/**
 * This function handles the image generation of the postcard via `generateImage()` function and also downloads the
 * image that is generated by assigning the link returned by that function to an achor-tag and invoking click event of
 * the anchor tag.
 * @summary Generates the image and downloads it with name `template.png`
 */

export const handleDownload = () => {
  const link = document.querySelector("#download") as HTMLAnchorElement;
  generateImage().then((dataUrl) => {
    link.href = dataUrl;
    link.click();
  });
};
