/**
 * @note Lookup importing modules in typescript.
 */

import domtoimage from "dom-to-image";

/**
 * This function handles the image generation of the postcard via `domtoimage.toPng(node)` function and also downloads the
 * image that is generated by assigning the link returned by that function to an achor-tag and invoking click event of
 * the anchor tag.
 * @summary Generates the image and downloads it with name `template.png`
 */

export const handleDownload = () => {
  const link = document.querySelector("#download") as HTMLAnchorElement;
  domtoimage
    .toPng(document.querySelector("#card__image")!)
    .then((dataUrl: string) => {
      link.href = dataUrl;
      link.click();
    });
};
